--------------------------------------------------------
--  DDL for Table COMP
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."COMP" 
   (	"CID" NUMBER(10,0), 
	"NAME" VARCHAR2(10 BYTE), 
	"CITY" VARCHAR2(10 BYTE), 
	"MOB" NUMBER(10,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
